export const ANNOUNCEMENT_ADD_REQUEST = 'ANNOUNCEMENT_ADD_REQUEST';
export const ANNOUNCEMENT_ADD_SUCCESS = 'ANNOUNCEMENT_ADD_SUCCESS';
export const ANNOUNCEMENT_ADD_FAIL = 'ANNOUNCEMENT_ADD_FAIL';

export const ANNOUNCEMENT_LIST_REQUEST = 'ANNOUNCEMENT_LIST_REQUEST';
export const ANNOUNCEMENT_LIST_SUCCESS = 'ANNOUNCEMENT_LIST_SUCCESS';
export const ANNOUNCEMENT_LIST_FAIL = 'ANNOUNCEMENT_LIST_FAIL';

export const ANNOUNCEMENT_DELETE_REQUEST = 'ANNOUNCEMENT_DELETE_REQUEST';
export const ANNOUNCEMENT_DELETE_SUCCESS = 'ANNOUNCEMENT_DELETE_SUCCESS';
export const ANNOUNCEMENT_DELETE_FAIL = 'ANNOUNCEMENT_DELETE_FAIL';