export const CALENDAR_EVENT_ADD_REQUEST = 'CALENDAR_EVENT_ADD_REQUEST';
export const CALENDAR_EVENT_ADD_SUCCESS = 'CALENDAR_EVENT_ADD_SUCCESS';
export const CALENDAR_EVENT_ADD_FAIL = 'CALENDAR_EVENT_ADD_FAIL';

export const CALENDAR_EVENT_LIST_REQUEST = 'CALENDAR_EVENT_LIST_REQUEST';
export const CALENDAR_EVENT_LIST_SUCCESS = 'CALENDAR_EVENT_LIST_SUCCESS';
export const CALENDAR_EVENT_LIST_FAIL = 'CALENDAR_EVENT_LIST_FAIL';

export const CALENDAR_EVENT_DELETE_REQUEST = 'CALENDAR_EVENT_DELETE_REQUEST';
export const CALENDAR_EVENT_DELETE_SUCCESS = 'CALENDAR_EVENT_DELETE_SUCCESS';
export const CALENDAR_EVENT_DELETE_FAIL = 'CALENDAR_EVENT_DELETE_FAIL';
