export const RESOURCE_ADD_REQUEST = 'RESOURCE_ADD_REQUEST';
export const RESOURCE_ADD_SUCCESS = 'RESOURCE_ADD_SUCCESS';
export const RESOURCE_ADD_FAIL = 'RESOURCE_ADD_FAIL';

export const RESOURCE_LIST_REQUEST = 'RESOURCE_LIST_REQUEST';
export const RESOURCE_LIST_SUCCESS = 'RESOURCE_LIST_SUCCESS';
export const RESOURCE_LIST_FAIL = 'RESOURCE_LIST_FAIL';

export const RESOURCE_DELETE_REQUEST = 'RESOURCE_DELETE_REQUEST';
export const RESOURCE_DELETE_SUCCESS = 'RESOURCE_DELETE_SUCCESS';
export const RESOURCE_DELETE_FAIL = 'RESOURCE_DELETE_FAIL';

